apiVersion: v1
kind: Service
metadata:
  name: galactus
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  selector:
    app: galactus
  ports:
  - port: 5858
    targetPort: 5858
    name: galactus
